### ISSUE TITLE
Not able to see screenshot added fro iOS.

### ISSUE THREAD

**Issue by rzee7** [Xamarin-Student-Ambassadors/app#6]
Hey Guys, 

I want to give a try for android based on current iOS version you guys developed. I tried to find It's new look by iOS screenshot updated in repo bu unfortunately I'm unable to see those screens getting 404 :( 

Thanks
RIYAZ

**Comment by tvand7093** [comment]
thanks for the heads up. I will be working on the overall project this weekend and will update the repo to include the screenshots.

**Comment by tvand7093** [comment]
Hey @rzee7, I updated the repo to include the iOS screenshots. You can use the links in the README file or you can navigate to the Mobile/iOS/Screenshots folder to view the images.
